In [1]:
import pandas as pd 

## Reading the csv file 
goalie_stats = pd.read_csv('game_goalie_stats.csv')
goalie_stats.head()

,game_id,player_id,team_id,timeOnIce,assists,goals,pim,shots,saves,powerPlaySaves,shortHandedSaves,evenSaves,shortHandedShotsAgainst,evenShotsAgainst,powerPlayShotsAgainst,decision,savePercentage,powerPlaySavePercentage,evenStrengthSavePercentage
0,2012030221,8468685,3,4540,0,0,0,48,45,10,1,34,1,36,11,L,93.750000,90.909091,94.444444
1,2012030221,8471695,6,4540,0,0,0,35,33,3,0,30,0,32,3,W,94.285714,100.000000,93.750000
2,2012030222,8468685,3,3600,0,0,0,32,27,1,2,24,2,29,1,L,84.375000,100.000000,82.758621
3,2012030222,8471695,6,3600,0,0,0,37,35,7,1,27,1,29,7,W,94.594595,100.000000,93.103448
4,2012030223,8471695,6,3600,0,0,0,24,23,2,0,21,0,22,2,W,95.833333,100.000000,95.454545

In [2]:
## Aggregating timeOnIce for each goalie (average time)
goalie_stats.groupby('player_id')['timeOnIce'].mean()

player_id
8455710    3527.906667
8459140    3192.250000
8460535    3065.866667
8460703    3278.040816
8460704    3499.789474
              ...
8479312    2617.090909
8479496    2804.272727
8480263     554.000000
8480382    3088.600000
8480420    3179.500000
Name: timeOnIce, Length: 173, dtype: float64

In [3]:
## Aggregating timeOnIce for each goalie (maximum time)
goalie_stats.groupby('player_id')['timeOnIce'].max().sort_values(ascending = False)

player_id
8475883    6972
8470645    6972
8471695    6725
8474889    6672
8471469    6672
           ...
8476412     767
8477990     753
8474855     712
8480263     554
8479115       8
Name: timeOnIce, Length: 173, dtype: int64