In [2]:
import pandas as pd 
import numpy as np

from sklearn.model_selection import train_test_split, RepeatedStratifiedKFold
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

heart = pd.read_csv('framingham.csv')
heart = heart.dropna()
heart.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [3]:
X = heart.drop(columns = 'TenYearCHD', axis = 1)
Y = heart['TenYearCHD']

In [15]:
xFeature_Imp = list()
for i in range(0, 100):

    data_temp = heart.sample(frac = 0.8, random_state = i)
    X = data_temp.drop(columns = 'TenYearCHD', axis = 1)
    Y = data_temp['TenYearCHD']

    RF_md = RandomForestClassifier(n_estimators = 500).fit(X, Y)
    Feature_Imp.append(RF_md.feature_importances_)

pd.DataFrame(Feature_Imp, columns = X.columns).apply(np.mean, axis = 0).sort_values(ascending = False)

sysBP              0.134974
BMI                0.127159
age                0.124375
totChol            0.122215
glucose            0.120018
diaBP              0.118977
heartRate          0.096085
cigsPerDay         0.050268
education          0.036915
male               0.021226
prevalentHyp       0.018218
currentSmoker      0.012567
BPMeds             0.007127
diabetes           0.006578
prevalentStroke    0.003299
dtype: float64