In [2]:
import pandas as pd 

## Reading the  csv file
churn = pd.read_csv('Customer_Churn.csv')
churn.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
import numpy as np

## Changing labels to 0-1
churn['Churn_numb'] = np.where(churn['Churn'] == 'No', 0, 1)
churn.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Churn_numb
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.5,No,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1

In [4]:
## Defining the input and target variables 
X = churn[['SeniorCitizen', 'tenure', 'MonthlyCharges']]
Y = churn['Churn_numb']

from sklearn.model_selection import train_test_split

## Splitting the data 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y)

In [5]:
## Logistic regression 
from sklearn.linear_model import LogisticRegression

## Building the logistic model 
logit_md = LogisticRegression().fit(X_train, Y_train)

## Predicting in the test dataset 
logit_pred = logit_md.predict_proba(X_test)[:, 1]
logit_pred_label = np.where(logit_pred < 0.35, 0, 1)

from sklearn.metrics import confusion_matrix, accuracy_score, recall_score

print('The confusion matrix is', confusion_matrix(Y_test, logit_pred_label))
print('The accuracy is', accuracy_score(Y_test, logit_pred_label))
print('The recall is', recall_score(Y_test, logit_pred_label))

The confusion matrix is [[822 213]
 [140 234]]
The accuracy is 0.7494677075940384
The recall is 0.6256684491978609

In [6]:
## Random forest
from sklearn.ensemble import RandomForestClassifier

## Building the random forest model 
RF_md = RandomForestClassifier().fit(X_train, Y_train)

## Predicting in the test dataset 
RF_pred = RF_md.predict_proba(X_test)[:, 1]
RF_pred_label = np.where(RF_pred < 0.35, 0, 1)

print('The confusion matrix is', confusion_matrix(Y_test, RF_pred_label))
print('The accuracy is', accuracy_score(Y_test, RF_pred_label))
print('The recall is', recall_score(Y_test, RF_pred_label))

The confusion matrix is [[815 220]
 [166 208]]
The accuracy is 0.7260468417317246
The recall is 0.5561497326203209